<a href="https://colab.research.google.com/github/YooSangH0/python2021/blob/main/python01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이썬 기초

## 파이썬
* 1990년 암스테르담의 귀도 반 로섬(Guido Van Rossum)이 개발한 **플랫폼 독립**적인 **인터프리터** 언어 
  + 변수를 선언할 때 타입을 지정하지 않음
  + 값을 할당하면 그때 동적으로 타입이 정해짐
  + 타입이 다를 경우 형 변환을 해줘야 연산에 사용할 수 있음
  
### 파이썬 기본 문법
* 주석 : 프로그램 실행과 관계 없이 코드에 대한 설명을 작성
  + 한줄 주석 : # 
  + 여러줄 주석 : 작은따옴표 세개('''주석내용''')

* 들여쓰기(indent)
  + 코드 블럭을 구성하기 위해서는 반드시 들여쓰기 해야함

* 행분리 : 역슬래쉬(\)
  + 하나의 명령을 여러 줄에 수행

* 행결합 : 세미콜론(;)
  + 한 줄에 여러 명령 수행

In [ ]:
'''
데이터분석으로 배우는 인공지능
작성자 : 김경민
'''
print("안녕 유상호")

안녕 유상호

## 변수(Variable)
* 필요한 데이터를 저장해 놓는 기억 공간의 별칭
* 변수 명 규칙
  + 영문 문자와 숫자 사용 : 대소문자 구분
  + 문자나 _(밑줄 문자)로 시작 : 숫자부터 시작하면 안 됨
  + 특수 문자(+, -, *, /, $, @, &, % 등)는 사용할 수 없음
  + python 키워드(if, for, while, and, or 등)는 사용할 수 없음

In [ ]:
x = '10'
x

'10'


### 파이썬 데이터 타입(Data Type)
* 정수 : 정수 자료형(int)
* 실수 : 부동소수점 자료형(float)
* 참거짓 : 참(True)과 거짓(False)를 나타내는 부울 자료형(bool)
* 문자열 : 문자열 자료형(str), 작은따옴표('')나 큰따옴표("")로 묶음


### 데이터 타입 확인 
* type() 함수

In [ ]:
x = 10
y = 20.5
b = True 
s = 'Hello Python!'

print(x, type(x))
print(y, type(y))
print(b, type(b))
print(s, type(s))

10 <class 'int'>
20.5 <class 'float'>
True <class 'bool'>
Hello Python! <class 'str'>



---

**생각해보기)**


---
10과 '10'은 같은 자료형일까?

## 형변환(type Casting)
* int() : 실수나 문자열을 정수로 변환
* float() : 정수나 문자열을 실수로 변환
* str() : 정수나 실수를 문자열로 변환

In [ ]:
x = '10' 
print(x, type(x))

x = int(x)
print(x, type(x))

10 <class 'str'>
10 <class 'int'>

In [ ]:
x = 10
y = '20'

print(str(x) + y)

1020

## 파이썬 기본 입출력

### 표준 입력 : input() 
* 표준 입력 장치인 키보드로 부터 입력
* 입력된 값은 문자열
```python
input() # 표준 입력장치로 부터 문자열을 입력
input('문자열') # 문자열을 출력하고 표준 입력장치로 부터 문자열 입력
```

In [ ]:
x = input()
y = input()

print(int(x) + int(y))

10
20
30

---

**생각해보기)**


---
정수나 실수 입력은 어떻게 받을까?

### 숫자 입력

In [ ]:
#정수 입력
 x = int(input())

#실수 입력
 y = float(input())


### 표준 출력 : print() 
* 표준 출력 장치인 모니터로 출력
```python
print(값1, 값2, ....) # 문자열을 출력하고 표준 입력장치로 부터 문자열 입력
```

* f-string
  + Python 신규 버전(3.6 이상) 부터 제공되는 기능
  + f'문자열' : f로 시작하는 문자열
    + 문자열 내부에 변수의 내용을 사용할 경우 {변수}
    + 문자열 내부에 실수인 변수를 소수점 처리할 경우 {실수변수:.소수점자리f}

In [ ]:
#소수정 처리 
x = 3.14159
s = f'x={x : 2f}'
print(s)

x= 3.141590

## 연산자
자료를 처리하기 위한 수식들을 결합하여 연산 동작을 수행하도록 하는 기호

+ 산술연산자
  - 수학적 계산을 수행할 때 사용하는 연산자
  - 사칙연산자(+, -, \*, /), 제곱(\**), 나머지(%), 나누기 결과 정수(//)

+ 비교연산자(관계연산자)
  - 비교할 때 사용하는 연산자
  - 등호(==), 같지 않음(!=), 부등호(<, >, <=, >=)

+ 논리연산자
  - 주어진 논리식을 판단하여, 참(true)과 거짓(false)을 결정하는 연산자
  - and(논리곱), or(논리합), not

+ 할당연산자
  - 변수에 값을 할당하기 위하여 사용하는 연산자

In [ ]:
#두 정수를 입력받아서 산술연산
x = 10%3
print(x)

1

## 조건문
프로그램의 실행 흐름을 바꾸고자 할 때 사용하는 제어문
 - 사용자가 지정한 조건에 따라 실행할 문장을 결정함
```python
if (조건식) : 
  명령문
elif (조건식) :
  명령문
else :
  명령문
```

- if 조건문 뒤에는 반드시 콜론(:)
- 바로 아래 문장부터 **if문에 속하는 모든 문장에 들여쓰기(indentation)**를 해야 함
- 파이썬에는 다른 언어에 있는 switch 문이 존재하지 않음 : if...elif...elif... 문으로 수행
- pass  : def 문이나 if 문처럼 코드 블록을 본문으로 갖는 표현에서 본문을 비워 둘 때 사용

In [ ]:
# 정수를 입력받아서 짝수/홀수 구분
x = int(input())

x % 2 == 0 
if x % 2 == 0 :
  print(f'{x}는 짝수')
else :
  print(f'{x}는 홀수')

5
5는 홀수

In [ ]:
# 성적을 입력받아서 70이상이면 Pass, 70점미만 60점이상 재수강, 60점미만 Fail

#1
x = float(input())

'''
if x >= 70 : print('pass')
else :
  if 70 > x >= 60 : print('재수강')
  else : print("Fail")
'''

#2
if x >= 70 : print(x, end = ':'); print('pass')
elif x >= 60 : print(x, end = ':'); print('재수강')
else : print(x, end = ':'); print('fail')

90
90.0:pass

## 반복문
+ **for문** : 컬렉션으로부터 하나씩 요소(element)를 가져와, 루프 내의 문장들을 실행
```python
for 변수 in 컬렉션:
    명령문
    명령문
    ...
```

 + **range() 함수**
```python
range(시작숫자, 종료숫자, step)
```
    + 결과는 시작숫자부터 종료숫자 바로 앞 숫자까지 컬렉션 생성
    + 값을 확인하기 위해서는 순서가 있는 리스트나 튜플 컬렉션으로 변환해야 함
    + 시작숫자를 생략하면 0부터 생성
    + step을 생략하면 1씩 증가

  + **in** 연산자, **not in** 연산자
    + 멤버십 연산자로 컬렉션에 속한 멤버를 확인하기 위한 연산자

+ **while문** : while 키워드 다음의 조건식이 참일 경우 계속 while 안의 블럭을 실행
```python
while 조건식:
    명령문
    명령문
    ...
```
+ **break 문**
  + 반복문 안에서 루프를 빠져나오기 위해 을 사용

+ **continue문**
  + 루프 블럭의 나머지 문장들을 실행하지 않고 다음 루프로 직접 돌아가게 함

In [ ]:
# 1에서 50까지 숫자 중의 3의 배수이면서 4의 배수인 수를 출력
# for문으로 

for n in range(1, 11) : 
  if n % 2 == 0 : break
  print(f'n = {n}')

n = 1

In [ ]:
# 1에서 50까지 숫자 중의 3의 배수이면서 4의 배수인 수를 출력
# while문으로 

n = int(input())

while n < 10 : 
  if n % 2 == 0 : break
  n = n + 1
  print(f'n = {n}')

5
n = 6

---
## **해결문제**


---
n이하의 피보나치 수열을 출력하시오.
 
 예) 1000이하
 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987

In [6]:
for n in range(1, 1001) :
  print(f'n = {n}')

n = 1
n = 2
n = 3
n = 4
n = 5
n = 6
n = 7
n = 8
n = 9
n = 10
n = 11
n = 12
n = 13
n = 14
n = 15
n = 16
n = 17
n = 18
n = 19
n = 20
n = 21
n = 22
n = 23
n = 24
n = 25
n = 26
n = 27
n = 28
n = 29
n = 30
n = 31
n = 32
n = 33
n = 34
n = 35
n = 36
n = 37
n = 38
n = 39
n = 40
n = 41
n = 42
n = 43
n = 44
n = 45
n = 46
n = 47
n = 48
n = 49
n = 50
n = 51
n = 52
n = 53
n = 54
n = 55
n = 56
n = 57
n = 58
n = 59
n = 60
n = 61
n = 62
n = 63
n = 64
n = 65
n = 66
n = 67
n = 68
n = 69
n = 70
n = 71
n = 72
n = 73
n = 74
n = 75
n = 76
n = 77
n = 78
n = 79
n = 80
n = 81
n = 82
n = 83
n = 84
n = 85
n = 86
n = 87
n = 88
n = 89
n = 90
n = 91
n = 92
n = 93
n = 94
n = 95
n = 96
n = 97
n = 98
n = 99
n = 100
n = 101
n = 102
n = 103
n = 104
n = 105
n = 106
n = 107
n = 108
n = 109
n = 110
n = 111
n = 112
n = 113
n = 114
n = 115
n = 116
n = 117
n = 118
n = 119
n = 120
n = 121
n = 122
n = 123
n = 124
n = 125
n = 126
n = 127
n = 128
n = 129
n = 130
n = 131
n = 132
n = 133
n = 134
n = 135
n = 136
n = 137
n = 138
n = 139
n = 140
n = 141
n = 142
n = 143
n = 144
n = 145
n = 146
n = 147
n = 148
n = 149
n = 150
n = 151
n = 152
n = 153
n = 154
n = 155
n = 156
n = 157
n = 158
n = 159
n = 160
n = 161
n = 162
n = 163
n = 164
n = 165
n = 166
n = 167
n = 168
n = 169
n = 170
n = 171
n = 172
n = 173
n = 174
n = 175
n = 176
n = 177
n = 178
n = 179
n = 180
n = 181
n = 182
n = 183
n = 184
n = 185
n = 186
n = 187
n = 188
n = 189
n = 190
n = 191
n = 192
n = 193
n = 194
n = 195
n = 196
n = 197
n = 198
n = 199
n = 200
n = 201
n = 202
n = 203
n = 204
n = 205
n = 206
n = 207
n = 208
n = 209
n = 210
n = 211
n = 212
n = 213
n = 214
n = 215
n = 216
n = 217
n = 218
n = 219
n = 220
n = 221
n = 222
n = 223
n = 224
n = 225
n = 226
n = 227
n = 228
n = 229
n = 230
n = 231
n = 232
n = 233
n = 234
n = 235
n = 236
n = 237
n = 238
n = 239
n = 240
n = 241
n = 242
n = 243
n = 244
n = 245
n = 246
n = 247
n = 248
n = 249
n = 250
n = 251
n = 252
n = 253
n = 254
n = 255
n = 256
n = 257
n = 258
n = 259
n = 260
n = 261
n = 262
n = 263
n = 264
n = 265
n = 266
n = 267
n = 268
n = 269
n = 270
n = 271
n = 272
n = 273
n = 274
n = 275
n = 276
n = 277
n = 278
n = 279
n = 280
n = 281
n = 282
n = 283
n = 284
n = 285
n = 286
n = 287
n = 288
n = 289
n = 290
n = 291
n = 292
n = 293
n = 294
n = 295
n = 296
n = 297
n = 298
n = 299
n = 300
n = 301
n = 302
n = 303
n = 304
n = 305
n = 306
n = 307
n = 308
n = 309
n = 310
n = 311
n = 312
n = 313
n = 314
n = 315
n = 316
n = 317
n = 318
n = 319
n = 320
n = 321
n = 322
n = 323
n = 324
n = 325
n = 326
n = 327
n = 328
n = 329
n = 330
n = 331
n = 332
n = 333
n = 334
n = 335
n = 336
n = 337
n = 338
n = 339
n = 340
n = 341
n = 342
n = 343
n = 344
n = 345
n = 346
n = 347
n = 348
n = 349
n = 350
n = 351
n = 352
n = 353
n = 354
n = 355
n = 356
n = 357
n = 358
n = 359
n = 360
n = 361
n = 362
n = 363
n = 364
n = 365
n = 366
n = 367
n = 368
n = 369
n = 370
n = 371
n = 372
n = 373
n = 374
n = 375
n = 376
n = 377
n = 378
n = 379
n = 380
n = 381
n = 382
n = 383
n = 384
n = 385
n = 386
n = 387
n = 388
n = 389
n = 390
n = 391
n = 392
n = 393
n = 394
n = 395
n = 396
n = 397
n = 398
n = 399
n = 400
n = 401
n = 402
n = 403
n = 404
n = 405
n = 406
n = 407
n = 408
n = 409
n = 410
n = 411
n = 412
n = 413
n = 414
n = 415
n = 416
n = 417
n = 418
n = 419
n = 420
n = 421
n = 422
n = 423
n = 424
n = 425
n = 426
n = 427
n = 428
n = 429
n = 430
n = 431
n = 432
n = 433
n = 434
n = 435
n = 436
n = 437
n = 438
n = 439
n = 440
n = 441
n = 442
n = 443
n = 444
n = 445
n = 446
n = 447
n = 448
n = 449
n = 450
n = 451
n = 452
n = 453
n = 454
n = 455
n = 456
n = 457
n = 458
n = 459
n = 460
n = 461
n = 462
n = 463
n = 464
n = 465
n = 466
n = 467
n = 468
n = 469
n = 470
n = 471
n = 472
n = 473
n = 474
n = 475
n = 476
n = 477
n = 478
n = 479
n = 480
n = 481
n = 482
n = 483
n = 484
n = 485
n = 486
n = 487
n = 488
n = 489
n = 490
n = 491
n = 492
n = 493
n = 494
n = 495
n = 496
n = 497
n = 498
n = 499
n = 500
n = 501
n = 502
n = 503
n = 504
n = 505
n = 506
n = 507
n = 508
n = 509
n = 510
n = 511
n = 512
n = 513
n = 514
n = 515
n = 516
n = 517
n = 518
n = 519
n = 520
n = 521
n = 522
n = 523
n = 524
n = 525
n = 526
n = 527
n = 528
n = 529
n = 530
n = 531
n = 532
n = 533
n = 534
n = 535
n = 536
n = 537
n = 538
n = 539
n = 540
n = 541
n = 542
n = 543
n = 544
n = 545
n = 546
n = 547
n = 548
n = 549
n = 550
n = 551
n = 552
n = 553
n = 554
n = 555
n = 556
n = 557
n = 558
n = 559
n = 560
n = 561
n = 562
n = 563
n = 564
n = 565
n = 566
n = 567
n = 568
n = 569
n = 570
n = 571
n = 572
n = 573
n = 574
n = 575
n = 576
n = 577
n = 578
n = 579
n = 580
n = 581
n = 582
n = 583
n = 584
n = 585
n = 586
n = 587
n = 588
n = 589
n = 590
n = 591
n = 592
n = 593
n = 594
n = 595
n = 596
n = 597
n = 598
n = 599
n = 600
n = 601
n = 602
n = 603
n = 604
n = 605
n = 606
n = 607
n = 608
n = 609
n = 610
n = 611
n = 612
n = 613
n = 614
n = 615
n = 616
n = 617
n = 618
n = 619
n = 620
n = 621
n = 622
n = 623
n = 624
n = 625
n = 626
n = 627
n = 628
n = 629
n = 630
n = 631
n = 632
n = 633
n = 634
n = 635
n = 636
n = 637
n = 638
n = 639
n = 640
n = 641
n = 642
n = 643
n = 644
n = 645
n = 646
n = 647
n = 648
n = 649
n = 650
n = 651
n = 652
n = 653
n = 654
n = 655
n = 656
n = 657
n = 658
n = 659
n = 660
n = 661
n = 662
n = 663
n = 664
n = 665
n = 666
n = 667
n = 668
n = 669
n = 670
n = 671
n = 672
n = 673
n = 674
n = 675
n = 676
n = 677
n = 678
n = 679
n = 680
n = 681
n = 682
n = 683
n = 684
n = 685
n = 686
n = 687
n = 688
n = 689
n = 690
n = 691
n = 692
n = 693
n = 694
n = 695
n = 696
n = 697
n = 698
n = 699
n = 700
n = 701
n = 702
n = 703
n = 704
n = 705
n = 706
n = 707
n = 708
n = 709
n = 710
n = 711
n = 712
n = 713
n = 714
n = 715
n = 716
n = 717
n = 718
n = 719
n = 720
n = 721
n = 722
n = 723
n = 724
n = 725
n = 726
n = 727
n = 728
n = 729
n = 730
n = 731
n = 732
n = 733
n = 734
n = 735
n = 736
n = 737
n = 738
n = 739
n = 740
n = 741
n = 742
n = 743
n = 744
n = 745
n = 746
n = 747
n = 748
n = 749
n = 750
n = 751
n = 752
n = 753
n = 754
n = 755
n = 756
n = 757
n = 758
n = 759
n = 760
n = 761
n = 762
n = 763
n = 764
n = 765
n = 766
n = 767
n = 768
n = 769
n = 770
n = 771
n = 772
n = 773
n = 774
n = 775
n = 776
n = 777
n = 778
n = 779
n = 780
n = 781
n = 782
n = 783
n = 784
n = 785
n = 786
n = 787
n = 788
n = 789
n = 790
n = 791
n = 792
n = 793
n = 794
n = 795
n = 796
n = 797
n = 798
n = 799
n = 800
n = 801
n = 802
n = 803
n = 804
n = 805
n = 806
n = 807
n = 808
n = 809
n = 810
n = 811
n = 812
n = 813
n = 814
n = 815
n = 816
n = 817
n = 818
n = 819
n = 820
n = 821
n = 822
n = 823
n = 824
n = 825
n = 826
n = 827
n = 828
n = 829
n = 830
n = 831
n = 832
n = 833
n = 834
n = 835
n = 836
n = 837
n = 838
n = 839
n = 840
n = 841
n = 842
n = 843
n = 844
n = 845
n = 846
n = 847
n = 848
n = 849
n = 850
n = 851
n = 852
n = 853
n = 854
n = 855
n = 856
n = 857
n = 858
n = 859
n = 860
n = 861
n = 862
n = 863
n = 864
n = 865
n = 866
n = 867
n = 868
n = 869
n = 870
n = 871
n = 872
n = 873
n = 874
n = 875
n = 876
n = 877
n = 878
n = 879
n = 880
n = 881
n = 882
n = 883
n = 884
n = 885
n = 886
n = 887
n = 888
n = 889
n = 890
n = 891
n = 892
n = 893
n = 894
n = 895
n = 896
n = 897
n = 898
n = 899
n = 900
n = 901
n = 902
n = 903
n = 904
n = 905
n = 906
n = 907
n = 908
n = 909
n = 910
n = 911
n = 912
n = 913
n = 914
n = 915
n = 916
n = 917
n = 918
n = 919
n = 920
n = 921
n = 922
n = 923
n = 924
n = 925
n = 926
n = 927
n = 928
n = 929
n = 930
n = 931
n = 932
n = 933
n = 934
n = 935
n = 936
n = 937
n = 938
n = 939
n = 940
n = 941
n = 942
n = 943
n = 944
n = 945
n = 946
n = 947
n = 948
n = 949
n = 950
n = 951
n = 952
n = 953
n = 954
n = 955
n = 956
n = 957
n = 958
n = 959
n = 960
n = 961
n = 962
n = 963
n = 964
n = 965
n = 966
n = 967
n = 968
n = 969
n = 970
n = 971
n = 972
n = 973
n = 974
n = 975
n = 976
n = 977
n = 978
n = 979
n = 980
n = 981
n = 982
n = 983
n = 984
n = 985
n = 986
n = 987
n = 988
n = 989
n = 990
n = 991
n = 992
n = 993
n = 994
n = 995
n = 996
n = 997
n = 998
n = 999
n = 1000



---
## **해결문제**


---
 밑변과 높이를 입력받아 삼각형의 면적을 구하시오.
 * 밑변과 높이는 정수형으로 입력

In [3]:
 a = int(input())
 b = int(input())

 print(a * b / 2)

2
1
1.0

---

**생각해보기)**


---
정수형으로 입력되는 밑변과 높이를 공백을 기준으로 한 줄로 입력받는다면?
* 예) 20 10